// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URL_Shortener.Data;

namespace URL_Shortener.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20211201141505_AddIndexesToURLsTable")]
    partial class AddIndexesToURLsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("URL_Shortener.Models.URLs", b =>
                {
                    b.Property<string>("ShortUrl")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ShortUrl");

                    b.HasIndex("SourceUrl", "ShortUrl");

                    b.ToTable("URLs");
                });
#pragma warning restore 612, 618
        }
    }
}
